# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/final/final.srcs/sources_1/ip/dcm_25M/dcm_25M.xci
# IP: The module: 'dcm_25M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/final/final.srcs/sources_1/ip/dcm_25M/dcm_25M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/final/final.srcs/sources_1/ip/dcm_25M/dcm_25M.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/final/final.srcs/sources_1/ip/dcm_25M/dcm_25M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/final/final.srcs/sources_1/ip/dcm_25M/dcm_25M.xci
# IP: The module: 'dcm_25M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/final/final.srcs/sources_1/ip/dcm_25M/dcm_25M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/final/final.srcs/sources_1/ip/dcm_25M/dcm_25M.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/final/final.srcs/sources_1/ip/dcm_25M/dcm_25M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_25M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
