# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qe8qWtifWxW6jYEzDTtZ_d5-W02L6WKw

#常用函數

1.print("格式字串"[,sep='分隔符號',end='換行符號，內定是\n'])
"""

print(1,2,3)
print(1,2,3,sep=' ')
print(1,2,3,sep=',')
print(1,2,3,sep=' ',end=' ')
print(4,5,6)

"""2.input("提示字串")鍵盤輸入，接收資料為字串str

3.type()回傳類別名稱

可以用int()轉換
"""

a = input("輸入:")
print(a,type(a))
b = int(a)
print(b,type(b))

a = 10
b = 20
c = a>b
print(c,type(c))#c是布林值
d=a==b#a是否等於b
print(d,type(d))

a = range(10)
print(a,type(a))
print(a[2])
for i in a:
  print(i,end=",")

a = 1256
print(type(a))
b = a/100
print(type(b))
c = int(b)
print(type(c))
print(a,b,c)

a = (1,"a")
print(a,type(a))
c,d=a #用這個方式解開tuple
print(c,type(c))
print(d,type(d))

"""#python常用的內建函數(二)
1.sorted()排序的內建函數

2.str()回傳字串物件

3.abs()傳回絕對值

4.max()傳回參數中的最大值

5.min()傳回參數中的最小值



"""

a = [1,2,5,7,3]
b = sorted(a)
print(a,type(a))
print(b,type(b))
c = sorted(a,reverse = True)
print(c,type(c))

a = 10
b = 20
c = a*b
print(a,'x',b,'=',c)
print(str(a)+'x'+str(b)+'='+str(c))
print(a,'x',b,'=',c,sep='')

a = "11"
b = int(a)
print(a,type(a))
print(b,type(b))
c = int(a,base=2)#二進制
print(c,type(c))
c = int(a,base=8)#八進制
print(c,type(c))
c = int(a,base=7)#七進制
print(c,type(c))
c = int(a,base=16)#十六進制
print(c,type(c))
#電腦用最多的是16進

"""#課後作業1"""

#課後作業 輸入兩個整數然後相加
a = input("輸入第一個整數:")
b = input("輸入第二個整數:")
c = int(a)+int(b)#轉成整數才能相加
print("相加答案=",c)

#課後作業 輸入兩個整數，求商和餘數
a = input("輸入第一個整數:")
b = input("輸入第二個整數:")
c = int(int(a)/int(b))#相除之後轉成整數後面位數會被捨去
d = int(a)%int(b)#取餘數
print("商=",c)
print("餘數=",d)

#課後作業 對調兩個數值
a = input("輸入a:")
b = input("輸入b:")
c = a #用一個c暫存值
a = b 
b = c
print("輸出a=",a)
print("輸出b=",b)

#課後作業 對調兩個數值
a = input("輸入a:")
b = input("輸入b:")
print("舊的(a,b)=(",a,",",b,")")
a,b=b,a
print("新的(a,b)=(",a,",",b,")")

#課後作業 輸入一個整數，判斷是奇數還是偶數
for i in range (1,3):
  a = input("輸入一個整數:")
  b = int(a)%2 #除2有餘數表示是奇數
  if (b==1):
    print("奇數")
  else:
    print("偶數")

"""#4-2 函數/自訂函數
*程式中的函數:定義一段可以重複呼叫並執行的程式碼

python自訂函數語法:

def 函數名稱(參數1,參數2,...):

      函數的敘述區塊
      return 回傳值

*無參數，無回傳值 VS 有參數，無回傳值
"""

def hello():
  print("hello")

hello()

hello()

def hello():
  print("hello")

#函數上下交換放沒關係

def hello(name):
  print('hello',name)

n = input("請輸入名字:")
hello(n)

"""練習1 印出10個分隔符號"""

print("==========")
print('='*10)

def printline(n):
  for i in range(n):
    print("=",end="")#要用半形，全形的話會分辨不出來
  print()#分行
printline(10)
printline(20)

def printline(p='-',n=10):#有初值
    print(p*n)
printline()#因為有初值所以可以都不給
printline('=')
printline('=',5)
printline('*',20)#沒有寫名字的話要照順序
printline(n=50,p='*')#可以直接給變數，所有變數都要放

"""練習2/3 變數生命週期，區域變數和全域變數"""

a = 10 #全域變數
def fun1():
  a = 5 #區域變數，只有在縮排裡面是這樣
  print('fun1中的變數a:',a)
#區域變數在縮排外面不存在
print('main中的變數a:',a)#全域變數
fun1()
print('main中的變數a:',a)#全域變數

a = 10 #全域變數
def fun1():
  global a #把全域變數抓進來用
  print('fun1中的變數a:',a)
  a = 100#改過全域變數
print('main中的變數a:',a)#全域變數
fun1()
print('main中的變數a:',a)#全域變數

"""練習4 函數的回傳值 計算面積

"""

#長方形面積
def area(length,width):
  return length*width

a = eval(input("長:"))
b = eval(input("寬:"))
#eval() 化為數值，有小數就float，不是就int
ans = area(a,b)
print("長=",a)
print("寬=",b)
print("面積=",ans)

#圓形面積
def area(r):
  return r*r*3.14159

a = eval(input("半徑:"))
ans = area(a)
print("半徑=",a)
print("面積=",ans)

"""練習五 函數的回傳值 平年閏年"""

#年分非4的倍數為平年，4的倍數非100倍數的為閏年，為100倍數但非400倍數為平年，400的倍數為閏年
def year(y):
  b = y%4
  c = y%100
  d = y%400
  if( b==0 and c!=0 or d==0):
    print("閏年")
  else:
    print("平年")

a = eval(input("年分"))
year(a)

#可以用Tuple實現多的回傳值
def year(y):
  b = y%4
  c = y%100
  d = y%400
  if( b==0 and c!=0 or d==0):
    return True,"閏年"
  else:
    return False,"平年"

a = eval(input("年分="))
ans = year(a)
print(ans,type(ans))
a,b=ans#解開
print(a,type(a))
print(b,type(b))

"""練習六 1加到n的總和"""

def plus(n):
  ans=0
  for i in range(1,n+1):
    #print(i,sep=",",end="")
    ans=ans+i
  return ans
a = eval(input("1加到n,n="))
ans = plus(a)
print('1加到',a,"=",ans)

"""#課後作業2"""

#課後作業 完成攝氏溫度和華氏溫度的轉換(F=9/5*C+32)
def tran(c):
  F=(9/5)*c+32
  return F
for i in range (1,3):
  a = eval(input("攝氏溫度(C)="))
  ans = tran(a)
  print("華氏溫度(F)=",ans)

#課後作業 完成平方公尺與坪的轉換(1平方公尺=0.3025坪)
def transpace(m):
  p=m*0.3025
  return p
for i in range (1,3):
  a = eval(input("平方公尺="))
  ans = transpace(a)
  print("坪數=",ans)

#課後作業 輸入開始和結束的西元年，計算共有幾個閏年
#年分非4的倍數為平年，4的倍數非100倍數的為閏年，為100倍數但非400倍數為平年，400的倍數為閏年
def year(y):
  b = y%4
  c = y%100
  d = y%400
  if( b==0 and c!=0 or d==0):
    return 1
  else:
    return 0

def count(start,end):
  co=0
  for i in range (start,end+1):
    k=year(i)
    if k==1:
      co=co+1
      #print(i)
    else:
      co=co
  return co

a = eval(input("開始年分="))
b = eval(input("結束年分="))
ans = count(a,b)
print("有",ans,"個閏年")

"""練習七,八 費氏數列"""

#第零項=0，第一項=1，第N項為前兩項之合
def fibonacci(n):
  f0=0
  f1=1
  print (f0,end=" ")
  print (f1,end=" ")
  for i in range(1,n):
    f2=f0+f1
    print (f2,end=" ")
    f0=f1
    f1=f2
n = eval(input("n="))
fibonacci(n)

#輸出第N項
def fibonacci2(n):
  f0=0
  f1=1
  ans=0
  for i in range(1,n):
    f2=f0+f1
    f0=f1
    f1=f2
    if i==(n-1):
      ans = f2
  return ans
n = eval(input("n="))
ans = fibonacci2(n)
print(ans)

#用Tuple精簡化
#用分號也可以併行
def fibonacci2(n):
  f0,f1=0,1
  ans=0
  for i in range(1,n):
    f0,f1=f1,f0+f1
    if i==(n-2):
      ans = f0+f1
  return ans
n = eval(input("n="))
ans = fibonacci2(n)
print(ans)

"""練習9 求最大公因數"""



"""#遞迴

練習1 階乘 Factorial 遞迴
"""

def fact(n):
  if n==1:
    return 1
  return n*fact(n-1)
ans=fact(5)
print(ans)

"""練習2 1加到n遞迴"""

def add(n):
  if n==1:
    return 1
  return n+fact(n-1)
a = input("n=")
ans=add(a)
print(ans)

"""練習3 費氏數列遞迴"""

def f(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  else:
    return f(n-1)+f(n-2)
    
a = int(input("n="))
ans=f(a)
print(ans)

"""練習4 最大公因數 遞迴"""

def gcd(m,n):
  if n==0:
    return m
  else:
    return gcd(n,m%n)
ans = gcd(36,10)
print(ans)

"""#END"""