# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/114Ht0kyh6BGX3Ao85NTTiNjNkh70TVlP

#數據操作

list
"""

Alphabet = ["A","B","C","D","E","F","G"] #以中括號開始，中括號結束的LIST
print(Alphabet)
print(Alphabet[2:3])
print(Alphabet[2:-2])
print(Alphabet[:-2])
print(Alphabet[2:])

Alphabet = ["A","B","C","D","E","F","G"]
Alphabet.append("H") #插入
print("append之後的結果=",Alphabet)
Alphabet.insert(1,"清除") #在前面的位置放入後面的東西
print("insert之後的結果=",Alphabet)
Alphabet2 = ["i","j","k"]
Alphabet.extend(Alphabet2)#組合兩個list
print("extend之後的結果=",Alphabet)
Alphabet.remove("清除")#清掉其中一個東西
print("remove之後的結果=",Alphabet)
Alphabet.pop(6)#清掉第六個位置的東西，要是不夠長預設清除最後面一個
print("pop之後的結果=",Alphabet)
Alphabet.clear()#清掉list全部資料
print("clear之後的結果=",Alphabet)

Alphabet = ["A","B","C","D","E","F","G"]
c=Alphabet.index("D")
print("index(\"D\")之後的結果=",c)
c=Alphabet.index("D",1)#從1開始找，跟上面那個相同位置不變(整體位置)
print("index(\"D\",1)之後的結果=",c)
c=Alphabet.index("D",3,5)#從三找到四
print("index(\"D\",3,5)之後的結果=",c)
c=Alphabet.count("D")
print("count(\"D\")之後的結果=",c)

Alphabet = ["C","B","D","E","F","A","G"]
print("原本的list=",Alphabet)
Alphabet.sort() #利用ASKII code比較
print("sort結果=",Alphabet)
Alphabet.reverse()#反排序
print("reverse結果=",Alphabet)

Alphabet = ["C","B","D","E","F","A","G"]
Alphabet2 = ["i","j","k"]
print("舊的Alphabet=",Alphabet)
print("舊的Alphabet2=",Alphabet2)
Alphabet2 = Alphabet.copy()
print("新的Alphabet=",Alphabet)
print("新的Alphabet=",Alphabet2)

"""Tuple"""

Alphabet = ("A","B","C","D","E","F","G") #以小括號開始，小括號結束的Tuple
print(Alphabet)
print(Alphabet[2:3])
print(Alphabet[2:-2])
print(Alphabet[:-2])
print(Alphabet[2:])
#只有count還有index能用
c=Alphabet.index("D",3,5)
print("index(\"D\",3,5)之後的結果=",c)
c=Alphabet.count("D")
print("count(\"D\")之後的結果=",c)

"""set"""

Alphabet = {"A","B","C","D","E","F","G"}
Alphabet2 = {"4","B","7","8","E","F","G"}
print(Alphabet)
Alphabet.remove("A")
print("removeA之後=",Alphabet)
Alphabet.discard("C")#忽略掉C
print("discard2之後=",Alphabet)
Z=Alphabet.difference(Alphabet2)#差集，在Alphabet裡面但不在Alphabet2裡面
print("差集Alphabet和Alphabet2之後",Z)
Z=Alphabet.union(Alphabet2)#聯集，且不重複
print("聯集Alphabet和Alphabet2之後",Z)
Z=Alphabet.intersection(Alphabet2)#交集，且不重複
print("交集Alphabet和Alphabet2之後",Z)
Z=Alphabet.symmetric_difference(Alphabet2)#對稱差集，互斥或
print("對稱差集Alphabet和Alphabet2之後",Z)
Alphabet.pop() #亂數
print("pop第一次之後=",Alphabet)
Alphabet.pop()
print("popˇ第二次之後=",Alphabet)

Revenger = {'美國隊長':'Roger','雷神索爾':'Thor','綠巨人':'Banner'}
x = Revenger.get("雷神索爾")
print(x)
x = Revenger.keys()
print(x)
x = Revenger.values()
print(x)
Revenger.pop("綠巨人")
print(Revenger)
Revenger.update({"蟻人":"Scott"})
print(Revenger)

"""條件判斷

"""

x = input('輸入成績等第:')
if x == '5A':
  print('獎金5000元')
else:
  print("再加油")

x = input('成績')
score = int(x)
if score >=60:
  print('及格')

#if判斷式練習
x = input('請輸入郵遞區號:')
if x =="710":
  print('台南市永康區')
elif x=="712":
  print('台南市新化區')
else:
  print('其他區域')

#課後作業 BMI計算
for i in range(1,7):
  x = input("請輸入身高(cm):")
  height = int(x)
  y = input("請輸入體重(kg):")
  weight =int(y)
  BMI = weight/((height/100)*(height/100))
  print("BMI=",BMI)
  if BMI<18.5:
    print("體重過輕")
  elif BMI<24:
    print("正常範圍")
  else:
    if BMI<27:
      print("過重")
    elif BMI<30:
     print("輕度肥胖")
    elif BMI<35:
     print("中度肥胖")
    else:
     print("重度肥胖")

#課後作業 一元二次方程式求解
    #HINT:用判斷式B平方-4AC=>相同解，不同解、無解
for i in range(1,4):
  print("解一元二次聯立方程式ax^2+bx+c=0")
  a = int(input("  請輸入係數a="))
  b = int(input("  請輸入係數b="))
  c = int(input("  請輸入係數c="))
  D=b**2-(4*a*c)
  if D<0:
    print("無解")
  elif D==0:
    ans = -b/(a*2)
    print("二相同實根，根為x=",ans)
  else:
    ans1= -b+D**0.5/(a*2)
    ans2= -b-D**0.5/(a*2)
    print("二不同實根，根為x=",ans1,"和x=",ans2)

"""迴圈"""

#for迴圈
for i in range(1,11):
  print(str(i) + '重複事件')#str(i)把數字轉成字串
for i in range(1,11,2):
  print(str(i) + '重複事件',end="")#end=""不換行

#while迴圈
i = 1#初始值
while i<11:#判斷式
  print(i," ",end="")
  i=i+1#加一

#課後作業 可被11整除的數
#HINT 奇數位數數字和-偶數位置數字和要是11的倍數或0
for i in range(1,3):
  x = input("請輸入一個數字=")
  number = int(x)
  number2 = int(x)
  number2 = int(number2/10)
  odd=0 
  even=0
  while(number>0):
    #print("number=",number)
    odd = odd + (number%10)
    #print(number%10)
    number = int(number/100)
    #print("odd=:",odd)
  while(number2>0):
    #print("number2=",number2)
    even = even + (number2%10)
    #print(number2%10)
    number2 = int(number2/100)
    #print("even=:",even)
  print("奇數位數的和=",odd)
  print("偶數位數的和=",even)
  print("兩數相減=",odd-even)
  m=(odd-even)%11
  if m==0:
    print("是11的倍數")
  else:
    print("不是11的倍數")

#課後作業 三角形繪製 
for i in range(1,31,2):
  j=0
  k=0
  while k<(15-(i-1)/2-1):
      print(" ",end="")
      k=k+1
  while j<i:
    print("*",end="")
    j=j+1
  print("")

#課後作業 空心三角形繪製 
for i in range(1,31,2):
  j=0
  k=0
  while k<(15-(i-1)/2-1):
      print(" ",end="")
      k=k+1
  if i < (31-2):
    while j<i:
      if j == i-1:
        print("*",end="")
        j=j+1
      elif j == 0:
        print("*",end="")
        j=j+1
      else:
        print(" ",end="")
        j=j+1
 
  else:
    while j<i:
        print("*",end="")
        j=j+1
  print("")

#課後作業 菱形繪製 1~15~1
for i in range(1,15,2):
  j=0
  k=0
  while k<(8-(i-1)/2-1):
      print(" ",end="")
      k=k+1
  while j<i:
    print("*",end="")
    j=j+1
  print("") 
for i in range(15,0,-2):
  j=0
  k=0
  while k<(8-(i-1)/2-1):
      print(" ",end="")
      k=k+1
  while j<i:
    print("*",end="")
    j=j+1
  print("")