# -*- coding: utf-8 -*-
"""mp02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lJCUgFtM79tRmUESItQZmrYpF1lePr0z

修改繪圖風格
"""

import matplotlib.pyplot as plt
print(plt.style.available)
plt.style.use('fivethirtyeight')
plt.plot([2,4,1,3])
plt.title("figure 1")
plt.xlabel('x')#X軸標籤
plt.ylabel('number')#Y軸標籤
#不管有多少資料都要放在show前
plt.show()

import matplotlib.pyplot as plt

plt.plot([1,2,3,4],[1,4,9,16],'ro--')
plt.axis([0,6,0,20])
plt.xlabel('x')#X軸標籤
plt.ylabel('number')#Y軸標籤
#不管有多少資料都要放在show前
plt.show()

"""2D平面繪圖"""

#同時放在同一張圖上
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(0,5,0.2)
plt.plot(x,x,'ro',x,x**2,'bs',x,x**3,'g^')
plt.show()