# -*- coding: utf-8 -*-
"""day0725.ipynb のコピー

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DSlU1U2HdJbXD6nvrdIR_n4nOTNOVTxy
"""



from google.colab import drive
drive.mount('/content/drive')

"""掛載雲端硬碟"""

!ls

"""查看內容

查看整數範圍
"""

a=10000000
b=23789746
a*b

"""進制"""

a=0b10101010
b=23
a*b

a=0o234
b=0xa2
a*b

"""浮點數"""

a=1.456
b=-5.6
a*b

"""指數表示"""

a=1.3e12
b=3.5e-12
a*b

"""Decimal 浮點數"""

import decimal as decfloat
d1 = decfloat.Decimal('12345678901234567890.12345678901234567890')
d2 = decfloat.Decimal('1E-20')
print(d1, '+', d2, '=',d1+d2)
print('Decimal浮點數預設的準確位數(包含整數和小數):',
      decfloat.getcontext().prec)

"""複數運算"""

A=3+4j
B=3-4j
A+B

"""字串"""

A="Hello World!"
B='新興科技'
C=' '
A+C+B

"""布林"""

a=10
b=30
a>b

a=10
b=10
a>=b

a='a'
b='b'
a>b

"""輸出(print)"""

print("Hell World")

"""字串格式化"""

A='Hello World'
B='Google colab'
print('%s\n%s'%(A,B))

A='Hello World!%s'%('Google colab')
print(A)

A=10
print('The number is %d'% A)

print('Hello world!\nGoogle colab')

print('Isn\'t, they said.')

msg='{},{},{}'.format('The number is:',5,6)
print(msg)

msg='{:s}{:d}'.format('The number is:',5)
print(msg)

"""字串裁切"""

msg='Hello World!東澳我們來了'
print(msg[0])

msg='Hello World!東澳我們來了'
print(msg[15])

msg='Hello World!東澳我們來了'
print(msg[-1])

msg='Hello World!東澳我們來了'
print(msg[:])

msg='Hello World!東澳我們來了'
print(msg[:12])

msg='Hello World!東澳我們來了'
print(msg[12:])

msg='Hello World!東澳我們來了'
print(msg[3:16])

"""輸入"""

a=input('輸入一個整數:')
a=int(a)
b=input('輸入另一個整數:')
b=int(b)
print('%d+%d=%d'%(a,b,a+b))

a, b, c = map(int, input().split())
print('{}{}{}'.format(a,b,c))

(3-3*4*4)/(3-2/3)