# -*- coding: utf-8 -*-
"""Dayone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19abu0I5OavU0ZZ0Fx92xWew7JjYURXR4

#基本操作

計算機

*CTRL+ENTER(執行)
"""

3+4

3/4

4**4
#次方

3-3*4

(3-3*(4**2))/(3+(2/3))
#一般PYTHON顯示大概16位

"""不同進位顯示

"""

0b01011100
#執行之後會用十進位顯示

0o567
#八進位

0x3ac
#16進位，小寫x大寫X都可以，16進位數字的字母可以用大寫或小寫

a=0b10101010
b=23
a*b
#做完會是十進制

a=0b10101010
b=23.1231
a/b
#做完會是十進制

a=1.3e12
b=3.5e-12
a*b
#指數表示法

"""import decimal 之後會講"""

import decimal as decfloat
d1 = decfloat.Decimal("122345678901234567890,12345678901234567890")
d2 = decfloat.Decimal("1E-20")
print(dl,"+",d2,"=",d1+d2)
print("Decimal浮點數預設的準確位數(包含整數和小數):",
          decfloat.getcontext().prec)

"""複數運算"""

a=3+4j
b=3-4j
a/b
#可以做複數運算

"""其他語法

"""

A="Hello World !"
B='Google colab'
C=" "
2*A+C+B
#可以用*2來重複輸出

A=10
B=100
A<B

A="a"
B="b"
A>B
#原則上是用ASKII code去比較的

"""PRINT相關"""

A="我"
B="你"
print(A>B)

a=10
b=11
c=a*b
print(c)

A=input("輸入一個整數:")
B=input("輸入另外一個整數:")
print(A+B)
#變成字串連結無法做加減乘除，input是字串

A=input("輸入一個整數:")
A=int(A)
B=input("輸入另外一個整數:")
B=int(B)
print(A+B)
#跟[34]的差異是轉成int來做計算

A=input("輸入一個整數:")
C=int(A)
B=input("輸入另外一個整數:")
D=int(B)
print("輸出結果:%d"%(C+D))
print("輸出結果:%s"%A)
print("輸入:%s\n%s"%(A,B))
print("輸入:%s\'%s"%(A,B))
#%s和%d要用小寫,要是只有一個引數(%s)的話用A,B會有錯,要像最下面兩行用兩個引數

A="Hello World!%s"%("GOOGLE colab")
print(A)
B=("Isn\'t, they said.")
print(B)
#右斜線是跳脫字元，可以保留逗號等等

"""字串處理"""

msg = '{},{},{}'.format("The number is:",5,6)
print(msg)
#msg是大括號的字串
msg = '{}{}{}'.format("The number is:",5,6)
print(msg)
#有沒有逗號的差異

msg = "hello world!東澳我們來了"
print(msg[0])
#抓某一個字出來，從0算到字串長度-1，空格也算一個
print(msg[3:16])

"""範例程式碼"""

name_score = input("請輸入姓名和成績，資料之間加入空格")
A,B = name_score.spilt()
a,b = map(int, input().spilt())
#int代表輸入的是整數，會把輸入分進去a和b兩個，不用轉換

"""作業"""

a=input("請輸入字串:")
b="hello, "
print(b+a)

a, b = map(int, input().split())
print (a+b)