# -*- coding: utf-8 -*-
"""Day4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHI6BpHzglB-Vc6F6Bg44DHDqYmF_Gz1

#函數與模組
"""

import math
math.floor(9.5)#取小於此數的最大整數
math.pow(2,3)#2的3次方
math.gcd(12,18)#最大公因數

import random
print(random.random())#小於1的隨機小數
print(random.uniform(1,3))#包含1和3
print(random.randrange(10))#指定終點
print(random.randrange(5,10))#指定前後
print(random.randrange(5,50,5))#可以加遞增值
print(random.randrange(-5,-50,-2))#可以是遞減
print(random.randint(1,10))#包含1和10
#括號內可以放變數

#random 字串處理的部分
import random
print(random.choice('apple'))
print(random.choice(('A','B','C')))#用小括號包起來弄成Tuple
print(random.choices(('A','B','C'),k=2))#可以選複數個但是會重複

#random 指定出現機率
import random
foods=['麥當勞','頂呱呱','必勝客']
print(random.choices(foods,weights=[90,70,50],k=10))

#不重複 用LIST
from random import sample
list1=[1,2,3,4,5,6,7,8,9]
print(sample(list1,3))

#洗牌的亂數排列
import random
fruit = ["apple","banana","peach","mango","melon"]
random.shuffle(fruit)
print(fruit)
list1=[1,2,3,4,5,6,7,8,9]
random.shuffle(list1)
list1

"""#類別"""

class Animal:
  def __init__(self,name,food,sound):
     self.name=name  #如果沒有東西要寫pass
     self.food=food
     self.sound=sound
  def eat(self):
     print("I am "+self.name+",I eat "+self.food+",我會"+self.sound)

a=Animal("dog","meat","汪汪叫")
b=Animal("cat","fish","喵喵叫")
a.eat()
b.eat()

"""#檔案處理"""

#寫入
line="123456789"
f=open("test_file.txt","w")
f.write("test test")
f.write(line)
f.close()

#讀取方法一
f=open("test_file.txt","r")
text=f.read()
print(text)
f.close()

#比較安全的讀取方法二
with open("test_file.txt","r") as file1:
  FileContent = file1.read()
  print(FileContent)

#一段一段讀
f=open("test_file.txt","r")
text=f.read(9)
print(text)
text=f.read(9)#第十個開始讀
print(text)
f.close()

#用STRING方式讀取
with open("test_file.txt","r") as file1:
  content = file1.readline()
  print(text,type(text))

"""#CSV檔處理"""

import csv
f=open("people.csv","a",newline="")#a 是指附加上去
tup1=("Bob",19)
writer = csv.writer(f)
writer.writerow(tup1)
tup2=("Joe",44)
writer.writerow(tup2)
tup3=("Candy",18)
writer.writerow(tup3)
f.close()

with open("people.csv","r") as

"""#JSON 處理"""

#檔案轉換
import json
jsonData = '{"Mon":"星期一","Tue":"星期二","Wed":"星期三","Thu":"星期四","Fri":"星期五","Sat":"星期六","Sun":"星期天"}'
data = json.loads(jsonData)
print(data["Mon"])

json_test = '''{"name":"My name","版本":"1.1"}'''
with open("config.json","w") as file1:
  test = file1.write(json_test)

import json
with open("config.json","r") as file2:
  data = json.load(file2)
  print(data)
  print("name:",data["name"])
  print("version:",data["版本"])

"""#錯誤處理"""

try:
#故意除以零
  print("#2 {0}除以零".format(2/0))
#數值除以零的錯誤
except ZeroDivisionError:
  print("#2 {0}不能除以零".format(2))

